In [1]:
# Importing necssary libraries
import pandas as pd

In [2]:
# Loading the dataset
dataset = pd.read_csv("insurance_pre.csv")
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [3]:
# One-hot encoding to handle categorical data(state)
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset.tail()    # displays only last 5 rows in the dataset

      age    bmi  children     charges  sex_male  smoker_yes
1333   50  30.97         3  10600.5483         1           0
1334   18  31.92         0   2205.9808         0           0
1335   18  36.85         0   1629.8335         0           0
1336   21  25.80         0   2007.9450         0           0
1337   61  29.07         0  29141.3603         0           1

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
# Feature selection or inputs
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent.head()

   age     bmi  children  sex_male  smoker_yes
0   19  27.900         0         0           1
1   18  33.770         1         1           0
2   28  33.000         3         1           0
3   33  22.705         0         1           0
4   32  28.880         0         1           0

In [6]:
# Target or output 
dependent = dataset[['charges']]
dependent.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [7]:
# Splitting data into training and testing sets
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(independent,dependent,test_size=0.25,random_state=0)

In [8]:
X_train.shape

(1003, 5)

In [9]:
X_test.shape

(335, 5)

In [10]:
Y_train.shape

(1003, 1)

In [11]:
Y_test.shape

(335, 1)

In [41]:
# Model Training 
from sklearn.ensemble import AdaBoostRegressor
regressor = AdaBoostRegressor(random_state=0, n_estimators=100,learning_rate=1,loss='linear')
regressor.fit(X_train,Y_train)

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

AdaBoostRegressor(learning_rate=1, n_estimators=100, random_state=0)

In [42]:
Y_pred = regressor.predict(X_test)
Y_pred

array([14695.08848317, 13929.73751178, 46470.97644494, 14695.08848317,
       13929.73751178,  7289.30784582,  4984.95658511, 13929.73751178,
        9724.96385803,  9724.96385803,  9724.96385803, 13929.73751178,
       11667.4722434 ,  7289.30784582, 20193.92428545, 13929.73751178,
       14695.08848317,  9724.96385803,  9724.96385803, 37243.46334889,
       24400.54040979, 14695.08848317, 14695.08848317, 25208.43501327,
        4984.95658511,  9724.96385803,  4984.95658511,  9724.96385803,
        4984.95658511, 13929.73751178,  9724.96385803, 46470.97644494,
       14695.08848317, 14695.08848317, 20193.92428545,  4984.95658511,
       13929.73751178, 37243.46334889, 44235.94992298,  4984.95658511,
        7289.30784582,  4984.95658511, 24400.54040979, 46470.97644494,
       37243.46334889,  9724.96385803, 13929.73751178,  9650.97275497,
        8360.53516702, 14695.08848317,  4984.95658511,  9724.96385803,
       25208.43501327, 46470.97644494, 14695.08848317,  4984.95658511,
        4984.95658511, 13929.73751178, 11878.18141809, 20088.99229155,
        4984.95658511, 46470.97644494, 20088.99229155, 13929.73751178,
       13929.73751178, 13929.73751178, 36769.15876481, 44235.94992298,
        9724.96385803,  9724.96385803, 14695.08848317, 14695.08848317,
       20193.92428545, 14695.08848317, 14695.08848317, 14695.08848317,
       12768.76631325, 13929.73751178, 20193.92428545, 46470.97644494,
       14695.08848317, 44235.94992298,  4984.95658511, 13929.73751178,
       44235.94992298, 20193.92428545,  9724.96385803,  4984.95658511,
       20088.99229155, 37243.46334889,  9724.96385803, 14695.08848317,
        4984.95658511, 13929.73751178,  7289.30784582,  9724.96385803,
       46470.97644494, 44235.94992298,  9724.96385803, 14695.08848317,
        4984.95658511,  9724.96385803,  9724.96385803, 44235.94992298,
       25208.43501327,  4984.95658511, 14695.08848317,  4984.95658511,
       14695.08848317, 46470.97644494, 14695.08848317,  9724.96385803,
       13929.73751178, 37243.46334889, 46470.97644494,  9724.96385803,
        8360.53516702, 13929.73751178, 20088.99229155, 13294.34272485,
       44235.94992298, 14695.08848317, 14695.08848317,  9724.96385803,
       13929.73751178,  9724.96385803, 25208.43501327, 24400.54040979,
       46470.97644494,  4984.95658511, 13929.73751178,  6847.80689167,
        9724.96385803, 13929.73751178, 26228.39224865, 44235.94992298,
       24400.54040979, 13929.73751178, 24400.54040979,  8360.53516702,
        4984.95658511, 14695.08848317, 13929.73751178, 14695.08848317,
        8360.53516702, 14695.08848317, 20088.99229155,  9724.96385803,
        4984.95658511, 14695.08848317,  8360.53516702, 37243.46334889,
       13929.73751178,  6847.80689167,  9724.96385803,  9724.96385803,
        9724.96385803,  6847.80689167, 13929.73751178, 13929.73751178,
        9724.96385803, 14695.08848317, 14695.08848317, 13929.73751178,
        4984.95658511,  9724.96385803, 20193.92428545,  9724.96385803,
        8360.53516702,  4984.95658511,  9724.96385803,  9724.96385803,
       11878.18141809,  4984.95658511,  9724.96385803,  9724.96385803,
        9724.96385803,  8360.53516702, 26228.39224865,  4984.95658511,
       14695.08848317,  9724.96385803, 14695.08848317,  4984.95658511,
        9724.96385803, 25208.43501327,  4984.95658511,  8360.53516702,
       14695.08848317, 13929.73751178, 46470.97644494,  9724.96385803,
        8360.53516702, 24400.54040979,  4984.95658511,  4984.95658511,
        9724.96385803,  9724.96385803,  9724.96385803,  8360.53516702,
       14695.08848317, 46470.97644494, 14695.08848317, 20193.92428545,
        9724.96385803, 46470.97644494,  9724.96385803, 14695.08848317,
        9724.96385803,  4984.95658511, 13929.73751178, 14695.08848317,
        9724.96385803,  4984.95658511,  9724.96385803,  4984.95658511,
        9724.96385803,  8360.53516702, 20088.99229155,  9724.96385803,
        9724.96385803,  9724.96385803, 13294.34272485,  4984.95658511,
       14695.08848317, 14695.08848317, 14695.08848317, 14695.08848317,
        9724.96385803,  4984.95658511,  4984.95658511, 13929.73751178,
       14695.08848317,  6847.80689167,  8360.53516702,  9724.96385803,
       13929.73751178, 37243.46334889,  8360.53516702, 14695.08848317,
        7289.30784582, 37243.46334889,  9724.96385803, 10621.32124343,
       11878.18141809, 14695.08848317,  9724.96385803, 11667.4722434 ,
        4984.95658511,  9650.97275497, 20193.92428545, 46470.97644494,
        9724.96385803,  9724.96385803,  4984.95658511,  4984.95658511,
       13929.73751178,  4984.95658511,  9724.96385803,  8360.53516702,
       13294.34272485, 25208.43501327, 46470.97644494, 20088.99229155,
        9724.96385803, 14695.08848317, 37243.46334889, 13294.34272485,
       44235.94992298,  4984.95658511, 37243.46334889,  9724.96385803,
       14695.08848317,  9724.96385803, 44235.94992298,  9724.96385803,
       14695.08848317, 13294.34272485,  9724.96385803, 20088.99229155,
       14695.08848317,  7289.30784582, 14695.08848317,  4984.95658511,
        9724.96385803,  9724.96385803,  9724.96385803, 24400.54040979,
        9724.96385803,  4984.95658511,  9724.96385803, 46470.97644494,
       13294.34272485,  9724.96385803, 14695.08848317, 14695.08848317,
       37243.46334889,  9724.96385803,  9724.96385803, 13929.73751178,
        4984.95658511,  9724.96385803, 20193.92428545, 20193.92428545,
       14695.08848317,  4984.95658511,  9724.96385803, 13929.73751178,
       14695.08848317, 20193.92428545, 20193.92428545,  9724.96385803,
       20193.92428545,  4984.95658511,  7289.30784582,  7289.30784582,
       12768.76631325,  6847.80689167, 10621.32124343, 44235.94992298,
        9724.96385803,  9724.96385803,  4984.95658511, 13294.34272485,
        4984.95658511, 14695.08848317, 46470.97644494, 20193.92428545,
       13929.73751178, 44235.94992298, 14695.08848317,  9724.96385803,
       13929.73751178,  9724.96385803, 26228.39224865])

In [43]:
# Model evaluation
from sklearn.metrics import r2_score
score = r2_score(Y_test,Y_pred)
score

0.8607981901870915

In [44]:
# Saving the model
import pickle
filename = "Random_Forest_Saved_Model.sav"
pickle.dump(regressor,open(filename,'wb'))