In [1]:
# Importing necssary libraries
import pandas as pd

In [2]:
# Loading the dataset
dataset = pd.read_csv("insurance_pre.csv")
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [3]:
# One-hot encoding to handle categorical data(state)
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset.tail()    # displays only last 5 rows in the dataset

      age    bmi  children     charges  sex_male  smoker_yes
1333   50  30.97         3  10600.5483         1           0
1334   18  31.92         0   2205.9808         0           0
1335   18  36.85         0   1629.8335         0           0
1336   21  25.80         0   2007.9450         0           0
1337   61  29.07         0  29141.3603         0           1

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
# Feature selection or inputs
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent.head()

   age     bmi  children  sex_male  smoker_yes
0   19  27.900         0         0           1
1   18  33.770         1         1           0
2   28  33.000         3         1           0
3   33  22.705         0         1           0
4   32  28.880         0         1           0

In [6]:
# Target or output 
dependent = dataset[['charges']]
dependent.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [7]:
# Splitting data into training and testing sets
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(independent,dependent,test_size=0.25,random_state=0)

In [8]:
X_train.shape

(1003, 5)

In [9]:
X_test.shape

(335, 5)

In [10]:
Y_train.shape

(1003, 1)

In [11]:
Y_test.shape

(335, 1)

In [12]:
# Installing LGboost
!pip install lightgbm

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lightgbm in c:\users\thiru\appdata\roaming\python\python313\site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in c:\users\thiru\appdata\roaming\python\python313\site-packages (from lightgbm) (2.2.3)
Requirement already satisfied: scipy in c:\users\thiru\appdata\roaming\python\python313\site-packages (from lightgbm) (1.15.2)

In [67]:
# Model Training 
from lightgbm import LGBMRegressor
regressor = LGBMRegressor(n_estimators=100,learning_rate=0.1,max_depth=-1,num_leaves=10,boosting_type='gbdt')
regressor.fit(X_train,Y_train)

LGBMRegressor(num_leaves=10)

In [68]:
Y_pred = regressor.predict(X_test)
Y_pred

array([12762.2040689 , 10056.62466421, 44975.68744878, 12658.44429644,
       10362.07631357,  5268.76497125,  1171.22385575, 13158.21577743,
        8811.68821175,  5834.84071102,  6711.77672246, 13229.57555164,
       10658.24449001,  6635.63592546, 19970.1931255 , 12143.25123374,
       15022.25863487,  4493.8284697 ,  6769.12453529, 35471.00381708,
       24012.08779914, 16089.70627142, 11634.51022336, 27202.34776745,
        3302.27069379,  6319.45044032,  4966.86007245,  7774.84801788,
        3589.68814086, 10492.15391244,  7274.66768539, 47952.76869426,
       15691.47308087, 12424.26068142, 18990.00181568,  4466.79762876,
       10407.38575149, 38054.770701  , 38704.95394017,  3619.48680474,
        5181.95136662,  4771.57257723, 19892.99051184, 47938.3337911 ,
       36035.70117737,  6613.8259573 , 12329.32447842,  7051.2381791 ,
        4974.64896803, 12220.6961911 ,  3274.80572655,  5804.71992158,
       26721.77140027, 43889.17103596, 11744.24781252,  6162.28647481,
        4922.1536038 , 10733.86776943, 10368.05858523, 18178.97020412,
        2256.68498276, 44881.25749853, 18077.34558494, 13425.10665064,
       15604.8268338 ,  8911.03192651, 34715.06146767, 38269.69443451,
        5170.71276245,  8425.07079505, 15554.25882503, 12425.00315436,
       18506.73141162, 15958.42211323, 15900.71113005, 16587.96620822,
        9358.86042173,  9302.45788643, 18900.22816362, 48027.64948467,
       10921.61242234, 47099.5477079 ,  3136.85662144, 10670.79945741,
       41552.13684034, 18657.59339174,  5081.33114675,  3640.46637962,
       16171.41612169, 39668.81882473,  5707.46806603, 11592.9513677 ,
        3146.21923846, 10013.26284194,  5777.1983537 ,  4785.56558141,
       44990.08890014, 40638.23871608,  6633.86209865, 10529.99354582,
        3399.89890668,  6579.91333871,  7735.68269548, 39831.93773419,
       25449.40339265,  3430.72934585, 11036.77549289,  4502.93984632,
       11953.3157754 , 46009.15821392, 12390.92304581,  5466.21991716,
       10319.19859576, 34071.52404949, 49109.39324862,  6959.52082611,
        2847.20934884, 10733.86776943, 17256.43771322,  9598.64873947,
       41822.71939318, 12036.81168445, 12893.90528129,  8286.83947133,
       11698.72369432,  5847.41478223, 25149.84982912, 25042.89509432,
       48281.74962451,  2408.19631101, 11202.35498694,  5075.65147026,
        6165.86181323, 10229.03477896, 28235.84832212, 37799.02319952,
       22785.21639813, 12149.19817836, 24812.87883037,  7704.37381661,
        3010.19944343, 13196.91761847, 14072.85442773, 11563.05719417,
        6030.56359659, 14551.36443683, 17365.4395656 ,  9827.56755489,
        2034.22564891, 12480.58345463,  8987.65166709, 40886.8529731 ,
       10233.12008717,  5467.97513766,  4876.33429329,  8710.41173723,
        4620.81755264,  3636.40691764, 12143.25123374, 10852.63153082,
        6201.550595  , 13009.05270622, 14409.67909677,  9017.26755711,
        3928.99404484,  6761.07117382, 15999.81663611,  8238.68775974,
        5849.95566895,  2278.04752122,  7658.27733099,  8328.1090161 ,
       11305.40012853,  3308.67686966,  8544.84437751,  6895.94770981,
        6026.7851898 ,  6702.16113416, 26934.57669696,  1353.0929847 ,
       14908.80252918,  6321.21221848, 11929.11483976,  4431.1945561 ,
        5995.3537904 , 27380.32500065,  3136.85662144,  3623.75999136,
       14303.14821925, 12016.19394569, 41834.81125281,  7986.60482483,
        5514.51841857, 24092.31885051,  4501.66689553,  5712.38749089,
        8416.11543872,  7438.06041409,  6978.85126286,  4780.55723751,
       12546.11560671, 46573.78966087, 14896.24847464, 17632.45130888,
        7306.94791586, 42879.30353318,  5425.85900018, 12300.55098269,
        7761.16457882,  2482.14686765, 10555.06007148, 14252.92530393,
        6503.50858445,  3031.47453753,  6751.21758956,  5263.58929093,
        7492.54178617,  5843.85231944, 15433.07723728,  7043.07417529,
        8934.61285955,  6824.3433074 ,  9957.13873938,  2975.68872809,
       11904.59973436, 14943.65836895, 19282.1702363 , 12239.64661369,
        5428.80576567,  2720.56772443,  4232.29614482,  9069.64637328,
       13595.34141259,  7049.26345694,  4686.73027562,  7710.76060175,
       14094.17660751, 34229.6617018 ,  6370.61895155, 13414.03344663,
        8425.08014367, 38100.90595376,  7104.35392152,  9432.17650358,
       10560.29011251, 11522.67248205,  4959.54063214,  9075.23884602,
        3727.64827728,  6387.2848877 , 19790.37072465, 45112.5365658 ,
        6172.08942521,  5081.33114675,  2190.30419976,  3021.32671334,
        9218.86326665,  2206.437497  ,  6376.92561213,  5676.28028863,
        7745.21946499, 27263.41360899, 45590.58562928, 17982.49813825,
        7001.37114807, 10565.1462067 , 42569.8945012 , 10141.76310942,
       39260.42899998,  3082.41862512, 36808.07992902,  7368.95550083,
       12115.16035671,  7732.63066927, 40125.9803789 ,  6466.9730256 ,
       10867.6782704 , 11536.61517619,  4883.84209405, 17031.25028079,
       13965.85835713,  5859.20169291, 15238.20785926,  4302.20601016,
        6907.78078386,  5608.57861509,  9458.71468574, 23194.15366518,
        4155.34139925,  1353.0929847 ,  3209.91391309, 48477.834377  ,
       11392.97500709,  4896.9634575 , 15869.57586852, 12546.11560671,
       34314.96767659,  9338.52455788,  7343.0263962 , 10153.60990933,
        4172.36671935,  6953.05003756, 17082.79406244, 17606.77515382,
       14672.91491909,  2720.56772443,  4201.32452502, 11333.74931475,
       12660.26618637, 15999.81663611, 20869.41085055,  7840.3801385 ,
       17351.12887923,  4242.27658468,  7622.91078974,  5777.1983537 ,
       12223.97953313,  3791.08917005,  8665.9395036 , 45970.27524483,
        5894.44150197,  5152.27546539,  1947.41204427, 10906.53586645,
        5901.89317037, 12007.81448898, 46563.10684511, 18751.44927309,
       10618.33326337, 46152.46920387, 16482.21620471,  7306.94791586,
       10207.88712517,  4746.01864119, 28325.82211893])

In [69]:
# Model evaluation
from sklearn.metrics import r2_score
score = r2_score(Y_test,Y_pred)
score

0.8980467960160975

In [31]:
# Saving the model
import pickle
filename = "LG_BOOST_Saved_Model.sav"
pickle.dump(regressor,open(filename,'wb'))