In [1]:
# Importing necssary libraries
import pandas as pd

In [2]:
# Loading the dataset
dataset = pd.read_csv("insurance_pre.csv")
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [3]:
# One-hot encoding to handle categorical data(state)
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset.tail()    # displays only last 5 rows in the dataset

      age    bmi  children     charges  sex_male  smoker_yes
1333   50  30.97         3  10600.5483         1           0
1334   18  31.92         0   2205.9808         0           0
1335   18  36.85         0   1629.8335         0           0
1336   21  25.80         0   2007.9450         0           0
1337   61  29.07         0  29141.3603         0           1

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
# Feature selection or inputs
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent.head()

   age     bmi  children  sex_male  smoker_yes
0   19  27.900         0         0           1
1   18  33.770         1         1           0
2   28  33.000         3         1           0
3   33  22.705         0         1           0
4   32  28.880         0         1           0

In [6]:
# Target or output 
dependent = dataset[['charges']]
dependent.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [7]:
# Splitting data into training and testing sets
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(independent,dependent,test_size=0.25,random_state=0)

In [8]:
X_train.shape

(1003, 5)

In [9]:
X_test.shape

(335, 5)

In [10]:
Y_train.shape

(1003, 1)

In [11]:
Y_test.shape

(335, 1)

In [32]:
# Model Training 
import xgboost as xgb
regressor = xgb.XGBRegressor(n_estimators=100,learning_rate=0.1,max_depth=2,subsample=0.8,colsample_bytree=0.8,random_state=0)
regressor.fit(X_train,Y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=2,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [33]:
Y_pred = regressor.predict(X_test)
Y_pred

array([12573.543 , 10855.289 , 45185.312 , 14676.984 ,  9735.303 ,
        4582.5815,  2577.077 , 12973.956 ,  7963.269 ,  6356.4043,
        6387.3477, 11981.01  ,  9193.324 ,  5976.317 , 20279.518 ,
       12141.543 , 14083.28  ,  4841.0635,  7666.989 , 35552.07  ,
       25923.354 , 14255.583 , 12030.694 , 25832.635 ,  3180.6436,
        6348.462 ,  4215.6187,  8377.377 ,  4613.5693, 10783.851 ,
        8195.149 , 46684.773 , 15403.743 , 12644.981 , 17802.98  ,
        4738.3076, 11626.628 , 38948.76  , 38992.5   ,  3410.064 ,
        4993.387 ,  4582.6123, 21928.08  , 45708.934 , 37136.855 ,
        5523.992 , 12141.543 ,  7156.006 ,  4907.4424, 12393.084 ,
        4973.4766,  5045.9243, 25851.705 , 45330.92  , 11914.986 ,
        5798.6597,  5269.3394, 10128.153 ,  9499.21  , 15329.009 ,
        2716.5623, 45246.438 , 16837.158 , 12285.652 , 13754.135 ,
       10984.757 , 34321.996 , 38229.918 ,  4465.94  ,  9576.323 ,
       14797.7705, 12574.321 , 19408.463 , 15498.804 , 14316.07  ,
       15037.072 ,  8128.3296, 10529.5205, 21777.625 , 46569.92  ,
       12065.141 , 43104.277 ,  2998.7378,  9420.473 , 41448.027 ,
       21516.58  ,  4993.3804,  4028.979 , 15651.208 , 39114.707 ,
        7408.1567, 12207.866 ,  4332.7   , 10104.423 ,  5935.8574,
        5693.0947, 43228.777 , 38940.836 ,  6613.939 , 11672.321 ,
        4428.1323,  6570.0825,  6579.9976, 38204.19  , 23582.049 ,
        3582.7795, 10773.191 ,  4864.2944, 12394.612 , 43688.668 ,
       12704.5205,  5636.3516, 10855.289 , 34713.03  , 45850.977 ,
        7845.1606,  2901.86  , 10128.153 , 15672.463 , 10034.86  ,
       42188.17  , 11107.097 , 14676.681 ,  7616.56  ,  9662.615 ,
        5429.6616, 25616.66  , 24773.816 , 46219.633 ,  3544.6284,
       10167.599 ,  3936.6729,  7586.799 ,  9329.666 , 34544.785 ,
       38163.14  , 22501.902 , 11536.569 , 25710.29  ,  5736.8257,
        3228.1582, 12576.947 , 12799.51  , 12013.242 ,  6068.728 ,
       15822.231 , 15774.247 ,  6060.993 ,  1780.091 , 12432.515 ,
        7560.1245, 39516.22  , 10911.29  ,  4200.1953,  4050.376 ,
        7693.6543,  4062.4612,  3472.5925, 12141.543 , 11808.69  ,
        5934.739 , 14219.323 , 14273.021 , 10810.653 ,  3930.7205,
        8101.344 , 16672.041 ,  7149.258 ,  5953.055 ,  3057.6929,
        6218.4834,  6693.784 , 10556.702 ,  5293.817 ,  6380.1646,
        7702.1914,  5097.9023,  6491.528 , 29273.43  ,  2055.4497,
       13925.783 ,  7688.031 , 12027.036 ,  4485.555 ,  6229.57  ,
       27497.863 ,  2998.7378,  3904.6023, 15157.978 , 11841.344 ,
       42098.883 ,  6748.02  ,  6390.3057, 24999.021 ,  4894.664 ,
        4051.8457,  7984.4946,  8148.7456,  7191.8647,  5394.697 ,
       12867.427 , 44255.55  , 14241.789 , 21382.537 ,  6458.2437,
       44143.273 ,  5408.1616, 11963.761 ,  8453.362 ,  1876.7932,
       10803.506 , 14966.613 ,  5919.679 ,  4839.458 ,  7389.588 ,
        3758.003 ,  7723.6123,  5872.094 , 16322.116 ,  7116.0566,
        8745.993 ,  7791.155 , 10334.5625,  3843.3806, 12199.538 ,
       15655.671 , 15145.852 , 11940.403 ,  6300.305 ,  3652.6924,
        3136.4707,  9702.81  , 14712.168 ,  6770.3135,  5196.651 ,
        8339.255 , 11494.603 , 36554.145 ,  6840.1987, 13311.526 ,
        7558.056 , 38191.4   ,  9200.116 ,  8413.637 ,  9931.716 ,
       12378.919 ,  4566.761 ,  9121.901 ,  2780.6812,  6780.7363,
       20993.27  , 45520.777 ,  6484.4995,  4993.3804,  2821.6526,
        1940.4863,  9331.417 ,  3649.7192,  6771.285 ,  4936.0894,
        8441.692 , 27430.598 , 43958.62  , 18043.102 ,  7389.588 ,
       11672.321 , 40256.555 , 10126.465 , 40258.34  ,  2615.0894,
       39906.152 ,  6774.1675, 12775.652 ,  6329.0728, 40110.52  ,
        6725.778 , 11858.192 ,  9898.575 ,  4062.4612, 15643.487 ,
       12704.454 ,  6724.968 , 14812.402 ,  3549.254 ,  7725.613 ,
        6370.4873,  9168.624 , 23116.39  ,  4019.171 ,  2055.4497,
        3595.8735, 46742.42  , 10471.909 ,  5693.0947, 14347.357 ,
       12867.427 , 36783.562 ,  8109.5137,  7025.3354, 11100.095 ,
        3635.896 ,  5294.572 , 18542.559 , 20011.05  , 15161.237 ,
        3652.6924,  5070.484 , 10561.284 , 11963.761 , 16547.713 ,
       23083.023 ,  8098.687 , 16811.514 ,  3865.3164,  6718.9277,
        5777.3745, 10447.696 ,  3487.525 ,  8134.9517, 44773.184 ,
        5483.5537,  5345.1543,  2264.6216, 10468.96  ,  5746.6953,
       12850.767 , 45252.734 , 19503.705 , 10734.319 , 42999.62  ,
       14114.733 ,  6458.2437, 11105.914 ,  7195.8267, 27954.854 ],
      dtype=float32)

In [34]:
# Model evaluation
from sklearn.metrics import r2_score
score = r2_score(Y_test,Y_pred)
score

0.902080774307251

In [35]:
# Saving the model
import pickle
filename = "XG_BOOST_Saved_Model.sav"
pickle.dump(regressor,open(filename,'wb'))